anvil:
# Change the prefix. You may use '&' color codes.
    prefix: "&8[&7Anvil&8]"

# Enable Vault Economy Support.
    economy: false

# If eco is enabled, how much should it cost to run the /anvil command.
    price: 10