# Anvil Configuration File
anvil:

# Change the prefix. You may use '&' color codes.
    prefix: "&8[&7Anvil&8]"

# Enable Vault Economy Support.
    economy: false
# If eco is enabled, how much should it cost to run the /anvil command.
    price: 10

# This message is sent to the player when using the command. You may use '&' color codes.
    message: "&9You have opened the anvil inventory"
# This message edits the message returned when a player does "/anvil help". You may use '&' color codes.
    helpmsg: "&cUsage: &6/anvil [&ahelp&6/&9reload&6]"
# No Permissions Message. You may use '&' color codes.
    NoPermMSG: "&4You don't have enough permissions."
# Change the unknown arguments message. You may use '&' color codes.
    ArgsMSG: "&cUnknown Arguments."
# If economy is true, This mesasge is sent if the player doesn't have enough money.
    NoMoneyMSG: "&cYou do not have enough money!"

# Message all ops on reload
    msgops: false

# Reload Message. You may use '&' color codes.
    ReloadMSG: "&aYou have reloaded configuration."